version: '3.8'

services:
  notes:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - SERVER_PORT=8000
      - CONNECTIONSTRING=mongodb://mongo:27017
    volumes:
      - ./:/app
    command: npm start

  mongo:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config: