version: '3.8'

services:
  notes:
    build:
      context: .
    ports:
      - 8000:3000
      - 9229:9229
    environment:
      - SERVER_PORT=3000
      - CONNECTIONSTRING=mongodb://mongo:27017/nest-shop
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:debug

  mongo:
    image: mongo:5.0.6
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config: